select_field = single_3d_field

identity_field{
}

single_3d_field{
    hash3dgrid{
      otype = HashGrid
      n_levels = 16
      n_features_per_level = 2
      log2_hashmap_size = 20
      base_resolution = 8
      per_level_scale = 1.45
    }
    net{
      otype = FullyFusedMLP
      activation = ReLU
      output_activation = ReLU
      n_neurons = 64
      n_hidden_layers = 2
    }
}

dual_3d_field{
    hash3dgrid_fine{
      otype = HashGrid
      n_levels = 12
      n_features_per_level = 2
      log2_hashmap_size = 19
      base_resolution = 8
      per_level_scale = 1.45
    }
    hash3dgrid_coarse{
      otype = HashGrid
      n_levels = 12
      n_features_per_level = 2
      log2_hashmap_size = 19
      base_resolution = 2
      per_level_scale = 1.4
    }
    net{
      otype = FullyFusedMLP
      activation = ReLU
      output_activation = ReLU
      n_neurons = 64
      n_hidden_layers = 2
    }
}
